import { writeFileSync, mkdirSync, appendFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const TELEMETRY_DIR = join(ROOT, 'logs', 'telemetry')
const SESSIONS_DIR = join(ROOT, 'logs', 'sessions')

export interface ScenarioGroupResult {
  name: string
  status: 'pass' | 'fail'
  error?: string
  durationMs: number
}

export interface ReportInput {
  results: ScenarioGroupResult[]
  iteration: number
  maxIterations: number
  passRate: number
  shipReady: boolean
}

function checkLabel(results: ScenarioGroupResult[], name: string): string {
  return results.some(r => r.name.includes(name) && r.status === 'fail') ? '❌ FAIL' : '✅ PASS'
}

export async function generateReport(input: ReportInput): Promise<void> {
  mkdirSync(TELEMETRY_DIR, { recursive: true })
  mkdirSync(SESSIONS_DIR, { recursive: true })

  const today = new Date().toISOString().slice(0, 10)
  const ts = new Date().toISOString()
  const telemetryFile = join(TELEMETRY_DIR, `${today}.jsonl`)
  const reportFile = join(SESSIONS_DIR, `${today}-sim-audit.md`)

  // Append JSONL telemetry
  for (const r of input.results) {
    appendFileSync(telemetryFile, JSON.stringify({
      ts,
      event: 'sim_scenario',
      name: r.name,
      status: r.status,
      latencyMs: r.durationMs,
      ...(r.error ? { error: r.error } : {}),
    }) + '\n')
  }
  appendFileSync(telemetryFile, JSON.stringify({
    ts,
    event: 'sim_run',
    total: input.results.length,
    passed: input.results.filter(r => r.status === 'pass').length,
    failed: input.results.filter(r => r.status === 'fail').length,
    iteration: input.iteration,
    maxIterations: input.maxIterations,
    shipReady: input.shipReady,
  }) + '\n')

  // Build markdown report
  const passed = input.results.filter(r => r.status === 'pass').length
  const total = input.results.length
  const verdict = input.shipReady ? '✅ SHIP READY' : '❌ NOT READY'

  const rows = input.results.map(r => {
    const status = r.status === 'pass' ? '✅ PASS' : '❌ FAIL'
    const notes = r.error ? r.error.slice(0, 100) : ''
    return `| \`${r.name}\` | ${status} | ${r.durationMs}ms | ${notes} |`
  }).join('\n')

  const failures = input.results.filter(r => r.status === 'fail')

  const md = `# Codex E2E Simulation Audit — ${today}

## Verdict: ${verdict}

- **Iterations run:** ${input.iteration} / ${input.maxIterations}
- **Pass rate:** ${passed} / ${total} (${Math.round(input.passRate * 100)}%)
- **Timestamp:** ${ts}

## Scenario Results

| Scenario | Status | Duration | Notes |
|----------|--------|----------|-------|
${rows}

## Failures

${failures.length === 0
  ? '_No failures — all scenarios passed._'
  : failures.map(r =>
      `### \`${r.name}\`\n\n\`\`\`\n${r.error ?? 'Unknown error'}\n\`\`\``
    ).join('\n\n')}

## Production Readiness Checklist

| Area | Status |
|------|--------|
| Auth (register, login, RBAC) | ${checkLabel(input.results, 'auth')} |
| Thread + Message CRUD | ${checkLabel(input.results, 'threads')} |
| Chat Completions (non-stream + SSE) | ${checkLabel(input.results, 'chat')} |
| Routing Intelligence | ${checkLabel(input.results, 'routing')} |
| Provider + Model APIs | ${checkLabel(input.results, 'providers')} |
| Telemetry Endpoints | ${checkLabel(input.results, 'telemetry')} |
| Admin Tenant Management | ${checkLabel(input.results, 'admin')} |
| Error / Edge Cases | ${checkLabel(input.results, 'errors')} |

---
_Generated by Codex E2E Simulation Framework_
`

  writeFileSync(reportFile, md, 'utf8')
  console.log(`\nReport:    ${reportFile}`)
  console.log(`Telemetry: ${telemetryFile}`)
}
